In [220]:
import pandas as pd
import numpy as np
import seaborn as sns
import math
import matplotlib.pyplot as plt
from sklearn import linear_model

from word2number import w2n
import warnings
warnings.filterwarnings("ignore")

In [221]:
# Loading data

url="https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv"
df=pd.read_csv(url)
df.head(100)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [222]:
df.dtypes

area          int64
bedrooms    float64
age           int64
price         int64
dtype: object

In [223]:
df.columns

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [224]:
df['bedrooms']

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [225]:
df.bedrooms.median()

4.0

In [226]:
df['bedrooms'] = df['bedrooms'].fillna(4)
df['bedrooms']

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [227]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df[['price']])

LinearRegression()

In [228]:
reg.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [229]:
reg.intercept_

array([221323.0018654])

In [230]:
#price of the house with 3300 SQ feet, 3 Bedrooms, 40 yrs

reg.predict([[3300,3,40]])

array([[532026.98416295]])

In [231]:
# y=m1x1+m2x2+m3x3+b
y=112.06244194*3300+ 23388.88007794*3+ -3231.71790863*40+221323.0018654
y

532026.98415602

In [232]:
# Loading data

url="https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv"
d=pd.read_csv(url)
d.head(10)


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [233]:
#Replacing the NAN with 0
d['experience']=d['experience'].fillna('zero')
d.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [234]:
d.dtypes

experience                     object
test_score(out of 10)         float64
interview_score(out of 10)      int64
salary($)                       int64
dtype: object

In [235]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [236]:
d.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [237]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score

7

In [238]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(7)
d['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [239]:
d.dtypes

experience                      int64
test_score(out of 10)         float64
interview_score(out of 10)      int64
salary($)                       int64
dtype: object

In [240]:
reg=linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [241]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [242]:
reg.predict([[12,10,10]])

array([93747.79628651])